# Generated by Django 3.2.5 on 2022-09-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_subname', models.TextField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('customer_type_id', models.IntegerField(blank=True, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
