# Generated by Django 3.2.5 on 2022-09-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_subname', models.TextField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('customer_type_id', models.IntegerField(blank=True, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('card_expiration_date', models.TextField()),
                ('card_issue_date', models.TextField()),
                ('card_cvv', models.CharField(max_length=3)),
                ('card_type', models.TextField()),
                ('card_brand_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
